# Initially snatched and adapted from libsodium .travis.yml

sudo: false

language:
- cpp

cache:
- ccache

os:
 - linux

compiler:
 - clang
 - gcc
 - g++

before_script:
 - mkdir -p "${HOME}/tmp"
 - ./autogen.sh

script:
 - ./configure --prefix "${HOME}/tmp" PKG_CONFIG_PATH="${HOME}/tmp/lib"
 - CCACHE_BASEDIR="`pwd`" make -j4 all
 - CCACHE_BASEDIR="`pwd`" make install
 - CCACHE_BASEDIR="`pwd`" make distcheck
